
export const ADD_CITY = "ADD_CITY";
export const START_ADDING_CITY_REQUEST = "START_ADDING_CITY_REQUEST";
export const COMPLETE_ADDING_CITY_REQUEST = "COMPLETE_ADDING_CITY_REQUEST";
export const FAIL_ADDING_CITY_REQUEST = "FAIL_ADDING_CITY_REQUEST";

export const REMOVE_CITY = "REMOVE_CITY";

export const GET_CITY_WEATHER_DATA = "GET_CITY_WEATHER_DATA";
export const START_GETING_DATA_REQUEST = "START_GETING_DATA_REQUEST";
export const COMPLETE_GETING_DATA_REQUEST = "COMPLETE_GETING_DATA_REQUEST";
export const FAIL_GETING_DATA_REQUEST = "FAIL_GETING_DATA_REQUEST";