
export const ADD_CITY = "ADD_CITY";
export const START_ADDING_CITY_REQUEST = "START_ADDING_CITY_REQUEST";
export const COMPLETE_ADDING_CITY_REQUEST = "COMPLETE_ADDING_CITY_REQUEST";
export const FAIL_ADDING_CITY_REQUEST = "FAIL_ADDING_CITY_REQUEST";

export const REMOVE_CITY = "REMOVE_CITY";

export const GET_CITY_WEATHER_DATA = "GET_CITY_WEATHER_DATA";
export const START_GETTING_DATA_REQUEST = "START_GETTING_DATA_REQUEST";
export const COMPLETE_GETTING_DATA_REQUEST = "COMPLETE_GETTING_DATA_REQUEST";
export const FAIL_GETTING_DATA_REQUEST = "FAIL_GETTING_DATA_REQUEST";
export const UPDATED_CITY_DATA = "UPDATED_CITY_DATA";

export const COMPLETE_PERSIST = "persist/REHYDRATE";